### ISSUE TITLE
Bad performance when animating

### ISSUE THREAD

**Issue by elpiel** [embedded-graphics/simulator#42]
- Version of embedded-graphics-simulator in use (if applicable): 0.3
- Version of embedded-graphics in use (if applicable): 0.7

## Description of the problem/feature request/other

It seems that the simulator has a very bad performance when it comes to doing animation with `SDL2`.
When I was testing I got ~15 FPS with `BinaryColor` & 8-9 FPS when using `Rgb888` (or `Rgb858`, I forgot which one).

One way I saw performance gets crippled even more is by using `scale > 1`.

Another performance bottleneck could be the creation of texture on each `Sdl2Window::update` call:

https://github.com/embedded-graphics/simulator/blob/96e8a36aa89a8434cc860599b80fcfe9bc77990a/src/window.rs#L249-L263

- Is there a valid case where the size of the framebuffer might change?
- Are there any other places which might cause bottlenecks or is it the constant update of the full-display image that's the bottleneck?

Here's an example that can be run to see the performance in FPS with a simple text (for the FPS) and a very small 360p display & `BinaryColor`:

https://github.com/LechevSpace/embedded-fps/blob/main/examples/embedded_graphics.rs

**Comment by rfuest** [comment]
The simulator performance isn't great, but it shouldn't be that bad. Did you run your tests in release mode?

> * Is there a valid case where the size of the framebuffer might change?
> * Are there any other places which might cause bottlenecks or is it the constant update of the full-display image that's the bottleneck?

I never measured the performance impact of this code, but I was aware that recreating the texture every frame isn't perfect when I wrote it. There was some kind of lifetime issue that prevented me from storing the texture for the entire lifetime of the window, if I remember correctly. I think that the sdl2 crate has a feature to opt into using unsafe code to work around this problem. But I never investigated this any further, because the change I implemented at that time was already a big improvement in performance and enough for my use cases.

I did write a prototype of a `wgpu` based GPU accelerated simulator some time ago, but that hasn't been released publicly. Using shaders to implement the scaling would have a much lower performance impact.

**Comment by jamwaffles** [comment]
The simulator is quite performant when run with `--release` but it's pretty much a necessity as performance tanks if the flag is omitted.

IIRC the simulator draws a small square for each pixel on the display, for scaling/spacing purposes which is inefficient but as @rfuest alluded to, good enough for most cases. Doing it in shaders is the ideal approach, but I'm not sure if SDL can do that in a cross platform way.

**Comment by elpiel** [comment]
Ok, thanks for all the feedback. Indeed it does improve a lot when running with `--release` flag, I got up to 230 FPS when running in release. It's still not ideal running in release all the time but I might look into it eventually.

It's good to know that there is such a performance impact which can be improved in the future :yum: 

![Screenshot from 2022-06-16 11-29-23](https://user-images.githubusercontent.com/8925621/174039788-de660e4a-faa9-483d-b8b1-45c91623b1a0.png)
